package com.forlove.discussionCircle.system.entity;

import java.util.Date;

public class TomForumPlate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_PLATE.PLATE_ID
     *
     * @mbggenerated
     */
    private Integer plateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_PLATE.PLATE_NUMBER
     *
     * @mbggenerated
     */
    private String plateNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_PLATE.PLATE_NAME
     *
     * @mbggenerated
     */
    private String plateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_PLATE.PLATE_PICTURE
     *
     * @mbggenerated
     */
    private String platePicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_PLATE.PLATE_DESCRIPTION
     *
     * @mbggenerated
     */
    private String plateDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_PLATE.POST_COUNT
     *
     * @mbggenerated
     */
    private Integer postCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_PLATE.ADMINISTRATORS
     *
     * @mbggenerated
     */
    private Integer empCode;

    public Integer getEmpCode() {
        return empCode;
    }

    public void setEmpCode(Integer empCode) {
        this.empCode = empCode;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_PLATE.CREATER
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_PLATE.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_PLATE.OPERATOR
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_PLATE.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_PLATE.DELETED
     *
     * @mbggenerated
     */
    private String deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_PLATE.PLATE_ID
     *
     * @return the value of TOM_FORUM_PLATE.PLATE_ID
     *
     * @mbggenerated
     */
    public Integer getPlateId() {
        return plateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_PLATE.PLATE_ID
     *
     * @param plateId the value for TOM_FORUM_PLATE.PLATE_ID
     *
     * @mbggenerated
     */
    public void setPlateId(Integer plateId) {
        this.plateId = plateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_PLATE.PLATE_NUMBER
     *
     * @return the value of TOM_FORUM_PLATE.PLATE_NUMBER
     *
     * @mbggenerated
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_PLATE.PLATE_NUMBER
     *
     * @param plateNumber the value for TOM_FORUM_PLATE.PLATE_NUMBER
     *
     * @mbggenerated
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber == null ? null : plateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_PLATE.PLATE_NAME
     *
     * @return the value of TOM_FORUM_PLATE.PLATE_NAME
     *
     * @mbggenerated
     */
    public String getPlateName() {
        return plateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_PLATE.PLATE_NAME
     *
     * @param plateName the value for TOM_FORUM_PLATE.PLATE_NAME
     *
     * @mbggenerated
     */
    public void setPlateName(String plateName) {
        this.plateName = plateName == null ? null : plateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_PLATE.PLATE_PICTURE
     *
     * @return the value of TOM_FORUM_PLATE.PLATE_PICTURE
     *
     * @mbggenerated
     */
    public String getPlatePicture() {
        return platePicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_PLATE.PLATE_PICTURE
     *
     * @param platePicture the value for TOM_FORUM_PLATE.PLATE_PICTURE
     *
     * @mbggenerated
     */
    public void setPlatePicture(String platePicture) {
        this.platePicture = platePicture == null ? null : platePicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_PLATE.PLATE_DESCRIPTION
     *
     * @return the value of TOM_FORUM_PLATE.PLATE_DESCRIPTION
     *
     * @mbggenerated
     */
    public String getPlateDescription() {
        return plateDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_PLATE.PLATE_DESCRIPTION
     *
     * @param plateDescription the value for TOM_FORUM_PLATE.PLATE_DESCRIPTION
     *
     * @mbggenerated
     */
    public void setPlateDescription(String plateDescription) {
        this.plateDescription = plateDescription == null ? null : plateDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_PLATE.POST_COUNT
     *
     * @return the value of TOM_FORUM_PLATE.POST_COUNT
     *
     * @mbggenerated
     */
    public Integer getPostCount() {
        return postCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_PLATE.POST_COUNT
     *
     * @param postCount the value for TOM_FORUM_PLATE.POST_COUNT
     *
     * @mbggenerated
     */
    public void setPostCount(Integer postCount) {
        this.postCount = postCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_PLATE.CREATER
     *
     * @return the value of TOM_FORUM_PLATE.CREATER
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_PLATE.CREATER
     *
     * @param creater the value for TOM_FORUM_PLATE.CREATER
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_PLATE.CREATE_TIME
     *
     * @return the value of TOM_FORUM_PLATE.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_PLATE.CREATE_TIME
     *
     * @param createTime the value for TOM_FORUM_PLATE.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_PLATE.OPERATOR
     *
     * @return the value of TOM_FORUM_PLATE.OPERATOR
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_PLATE.OPERATOR
     *
     * @param operator the value for TOM_FORUM_PLATE.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_PLATE.UPDATE_TIME
     *
     * @return the value of TOM_FORUM_PLATE.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_PLATE.UPDATE_TIME
     *
     * @param updateTime the value for TOM_FORUM_PLATE.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_PLATE.DELETED
     *
     * @return the value of TOM_FORUM_PLATE.DELETED
     *
     * @mbggenerated
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_PLATE.DELETED
     *
     * @param deleted the value for TOM_FORUM_PLATE.DELETED
     *
     * @mbggenerated
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }
}