package com.forlove.discussionCircle.system.entity;

import java.util.Date;

public class TomForumPost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_POST.POST_ID
     *
     * @mbggenerated
     */
    private Integer postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_POST.PLATE_ID
     *
     * @mbggenerated
     */
    private Integer plateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_POST.POST_TITLE
     *
     * @mbggenerated
     */
    private String postTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_POST.POST_PICTURE
     *
     * @mbggenerated
     */
    private String postPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_POST.POST_DETAILS
     *
     * @mbggenerated
     */
    private String postDetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_POST.POST_STATUS
     *
     * @mbggenerated
     */
    private String postStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_POST.COMMENT_COUNT
     *
     * @mbggenerated
     */
    private Integer commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_POST.PRAISE_COUNT
     *
     * @mbggenerated
     */
    private Integer praiseCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_POST.VIEW_COUNT
     *
     * @mbggenerated
     */
    private Integer viewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_POST.EMP_CODE
     *
     * @mbggenerated
     */
    private String empCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_POST.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_FORUM_POST.DELETED
     *
     * @mbggenerated
     */
    private String deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_POST.POST_ID
     *
     * @return the value of TOM_FORUM_POST.POST_ID
     *
     * @mbggenerated
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_POST.POST_ID
     *
     * @param postId the value for TOM_FORUM_POST.POST_ID
     *
     * @mbggenerated
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_POST.PLATE_ID
     *
     * @return the value of TOM_FORUM_POST.PLATE_ID
     *
     * @mbggenerated
     */
    public Integer getPlateId() {
        return plateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_POST.PLATE_ID
     *
     * @param plateId the value for TOM_FORUM_POST.PLATE_ID
     *
     * @mbggenerated
     */
    public void setPlateId(Integer plateId) {
        this.plateId = plateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_POST.POST_TITLE
     *
     * @return the value of TOM_FORUM_POST.POST_TITLE
     *
     * @mbggenerated
     */
    public String getPostTitle() {
        return postTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_POST.POST_TITLE
     *
     * @param postTitle the value for TOM_FORUM_POST.POST_TITLE
     *
     * @mbggenerated
     */
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle == null ? null : postTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_POST.POST_PICTURE
     *
     * @return the value of TOM_FORUM_POST.POST_PICTURE
     *
     * @mbggenerated
     */
    public String getPostPicture() {
        return postPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_POST.POST_PICTURE
     *
     * @param postPicture the value for TOM_FORUM_POST.POST_PICTURE
     *
     * @mbggenerated
     */
    public void setPostPicture(String postPicture) {
        this.postPicture = postPicture == null ? null : postPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_POST.POST_DETAILS
     *
     * @return the value of TOM_FORUM_POST.POST_DETAILS
     *
     * @mbggenerated
     */
    public String getPostDetails() {
        return postDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_POST.POST_DETAILS
     *
     * @param postDetails the value for TOM_FORUM_POST.POST_DETAILS
     *
     * @mbggenerated
     */
    public void setPostDetails(String postDetails) {
        this.postDetails = postDetails == null ? null : postDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_POST.POST_STATUS
     *
     * @return the value of TOM_FORUM_POST.POST_STATUS
     *
     * @mbggenerated
     */
    public String getPostStatus() {
        return postStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_POST.POST_STATUS
     *
     * @param postStatus the value for TOM_FORUM_POST.POST_STATUS
     *
     * @mbggenerated
     */
    public void setPostStatus(String postStatus) {
        this.postStatus = postStatus == null ? null : postStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_POST.COMMENT_COUNT
     *
     * @return the value of TOM_FORUM_POST.COMMENT_COUNT
     *
     * @mbggenerated
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_POST.COMMENT_COUNT
     *
     * @param commentCount the value for TOM_FORUM_POST.COMMENT_COUNT
     *
     * @mbggenerated
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_POST.PRAISE_COUNT
     *
     * @return the value of TOM_FORUM_POST.PRAISE_COUNT
     *
     * @mbggenerated
     */
    public Integer getPraiseCount() {
        return praiseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_POST.PRAISE_COUNT
     *
     * @param praiseCount the value for TOM_FORUM_POST.PRAISE_COUNT
     *
     * @mbggenerated
     */
    public void setPraiseCount(Integer praiseCount) {
        this.praiseCount = praiseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_POST.VIEW_COUNT
     *
     * @return the value of TOM_FORUM_POST.VIEW_COUNT
     *
     * @mbggenerated
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_POST.VIEW_COUNT
     *
     * @param viewCount the value for TOM_FORUM_POST.VIEW_COUNT
     *
     * @mbggenerated
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_POST.EMP_CODE
     *
     * @return the value of TOM_FORUM_POST.EMP_CODE
     *
     * @mbggenerated
     */
    public String getEmpCode() {
        return empCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_POST.EMP_CODE
     *
     * @param empCode the value for TOM_FORUM_POST.EMP_CODE
     *
     * @mbggenerated
     */
    public void setEmpCode(String empCode) {
        this.empCode = empCode == null ? null : empCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_POST.CREATE_TIME
     *
     * @return the value of TOM_FORUM_POST.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_POST.CREATE_TIME
     *
     * @param createTime the value for TOM_FORUM_POST.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_FORUM_POST.DELETED
     *
     * @return the value of TOM_FORUM_POST.DELETED
     *
     * @mbggenerated
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_FORUM_POST.DELETED
     *
     * @param deleted the value for TOM_FORUM_POST.DELETED
     *
     * @mbggenerated
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }
}