package com.forlove.discussionCircle.system.entity;

import java.util.Date;

public class TomPostComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_POST_COMMENT.POST_COMMENT_ID
     *
     * @mbggenerated
     */
    private Integer postCommentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_POST_COMMENT.EMP_CODE
     *
     * @mbggenerated
     */
    private String empCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_POST_COMMENT.EMP_NAME
     *
     * @mbggenerated
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_POST_COMMENT.COMMENT_DETAILS
     *
     * @mbggenerated
     */
    private String commentDetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_POST_COMMENT.PRAISE_COUNT
     *
     * @mbggenerated
     */
    private Integer praiseCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_POST_COMMENT.POST_ID
     *
     * @mbggenerated
     */
    private Integer postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_POST_COMMENT.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_POST_COMMENT.DELETED
     *
     * @mbggenerated
     */
    private String deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_POST_COMMENT.POST_COMMENT_ID
     *
     * @return the value of TOM_POST_COMMENT.POST_COMMENT_ID
     *
     * @mbggenerated
     */
    public Integer getPostCommentId() {
        return postCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_POST_COMMENT.POST_COMMENT_ID
     *
     * @param postCommentId the value for TOM_POST_COMMENT.POST_COMMENT_ID
     *
     * @mbggenerated
     */
    public void setPostCommentId(Integer postCommentId) {
        this.postCommentId = postCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_POST_COMMENT.EMP_CODE
     *
     * @return the value of TOM_POST_COMMENT.EMP_CODE
     *
     * @mbggenerated
     */
    public String getEmpCode() {
        return empCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_POST_COMMENT.EMP_CODE
     *
     * @param empCode the value for TOM_POST_COMMENT.EMP_CODE
     *
     * @mbggenerated
     */
    public void setEmpCode(String empCode) {
        this.empCode = empCode == null ? null : empCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_POST_COMMENT.EMP_NAME
     *
     * @return the value of TOM_POST_COMMENT.EMP_NAME
     *
     * @mbggenerated
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_POST_COMMENT.EMP_NAME
     *
     * @param empName the value for TOM_POST_COMMENT.EMP_NAME
     *
     * @mbggenerated
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_POST_COMMENT.COMMENT_DETAILS
     *
     * @return the value of TOM_POST_COMMENT.COMMENT_DETAILS
     *
     * @mbggenerated
     */
    public String getCommentDetails() {
        return commentDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_POST_COMMENT.COMMENT_DETAILS
     *
     * @param commentDetails the value for TOM_POST_COMMENT.COMMENT_DETAILS
     *
     * @mbggenerated
     */
    public void setCommentDetails(String commentDetails) {
        this.commentDetails = commentDetails == null ? null : commentDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_POST_COMMENT.PRAISE_COUNT
     *
     * @return the value of TOM_POST_COMMENT.PRAISE_COUNT
     *
     * @mbggenerated
     */
    public Integer getPraiseCount() {
        return praiseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_POST_COMMENT.PRAISE_COUNT
     *
     * @param praiseCount the value for TOM_POST_COMMENT.PRAISE_COUNT
     *
     * @mbggenerated
     */
    public void setPraiseCount(Integer praiseCount) {
        this.praiseCount = praiseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_POST_COMMENT.POST_ID
     *
     * @return the value of TOM_POST_COMMENT.POST_ID
     *
     * @mbggenerated
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_POST_COMMENT.POST_ID
     *
     * @param postId the value for TOM_POST_COMMENT.POST_ID
     *
     * @mbggenerated
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_POST_COMMENT.CREATE_TIME
     *
     * @return the value of TOM_POST_COMMENT.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_POST_COMMENT.CREATE_TIME
     *
     * @param createTime the value for TOM_POST_COMMENT.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_POST_COMMENT.DELETED
     *
     * @return the value of TOM_POST_COMMENT.DELETED
     *
     * @mbggenerated
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_POST_COMMENT.DELETED
     *
     * @param deleted the value for TOM_POST_COMMENT.DELETED
     *
     * @mbggenerated
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }
}