package com.forlove.discussionCircle.system.entity;

import java.util.Date;

public class TomPostFavor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_POST_FAVOR.POST_ID
     *
     * @mbggenerated
     */
    private Integer postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_POST_FAVOR.EMP_CODE
     *
     * @mbggenerated
     */
    private String empCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_POST_FAVOR.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_POST_FAVOR.DELETED
     *
     * @mbggenerated
     */
    private String deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_POST_FAVOR.POST_ID
     *
     * @return the value of TOM_POST_FAVOR.POST_ID
     *
     * @mbggenerated
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_POST_FAVOR.POST_ID
     *
     * @param postId the value for TOM_POST_FAVOR.POST_ID
     *
     * @mbggenerated
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_POST_FAVOR.EMP_CODE
     *
     * @return the value of TOM_POST_FAVOR.EMP_CODE
     *
     * @mbggenerated
     */
    public String getEmpCode() {
        return empCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_POST_FAVOR.EMP_CODE
     *
     * @param empCode the value for TOM_POST_FAVOR.EMP_CODE
     *
     * @mbggenerated
     */
    public void setEmpCode(String empCode) {
        this.empCode = empCode == null ? null : empCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_POST_FAVOR.CREATE_TIME
     *
     * @return the value of TOM_POST_FAVOR.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_POST_FAVOR.CREATE_TIME
     *
     * @param createTime the value for TOM_POST_FAVOR.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_POST_FAVOR.DELETED
     *
     * @return the value of TOM_POST_FAVOR.DELETED
     *
     * @mbggenerated
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_POST_FAVOR.DELETED
     *
     * @param deleted the value for TOM_POST_FAVOR.DELETED
     *
     * @mbggenerated
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }
}