package com.forlove.discussionCircle.system.dao;


import com.forlove.discussionCircle.system.entity.TomPostCommentPraise;

public interface TomPostCommentPraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_POST_COMMENT_PRAISE
     *
     * @mbggenerated
     */
    int insert(TomPostCommentPraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_POST_COMMENT_PRAISE
     *
     * @mbggenerated
     */
    int insertSelective(TomPostCommentPraise record);
}