package com.forlove.discussionCircle.system.dao;

import com.chinamobo.ele.system.entity.TomPostFavor;

public interface TomPostFavorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_POST_FAVOR
     *
     * @mbggenerated
     */
    int insert(TomPostFavor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_POST_FAVOR
     *
     * @mbggenerated
     */
    int insertSelective(TomPostFavor record);
}