package com.forlove.discussionCircle.system.dao;


import com.forlove.discussionCircle.system.entity.TomPostPraise;

public interface TomPostPraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_POST_PRAISE
     *
     * @mbggenerated
     */
    int insert(TomPostPraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_POST_PRAISE
     *
     * @mbggenerated
     */
    int insertSelective(TomPostPraise record);
}